

BehaviorEvent =  {}

BehaviorEvent.EventName = 
{
	"BeforeParry",
	"Parry",
	"FirstCollide",
	"BeforeCollide",
	"Collide",
	"FirstTrigger",
	"BeforeAttack",
	"Attack",
	"OnAttackNpc",
	"JumpDodge",
	"JumpBeDodge",
	"BeforeDodge",
	"BeforeBeDodge",
	"Dodge",
	"BeDodge",
	"SkillPointChangeBefore",
	"SkillPointChangeAfter",
	"OnEntityCollision",
	"EnterElementStateReady",
	"PathFindingEnd",
	"BerforeHit",
	"BeforeHit",
	"Hit",
	"HitGround",
	"PartHit",
	"PartDestroy",
	"ReboundAttack",
	"CastSkill",
	"FinishSkill",
	"BreakSkill",
	"ClearSkill",
	"SkillFrameUpdate",

	"EnterTrigger",
	"ExitTrigger",
	"ExtraEnterTrigger",
	"ExtraExitTrigger",
	"EnterArea",
	"ExitArea",

	"Born",
	"Death",
	"DeathEnter",
	"Die",
	"Revive",
	"AddBuff",
	"RemoveEntity",
	"RemoveBuff",
	"AddEntitySign",
	"RemoveEntitySign",
	"AddSkillSign",
	"EntityStateChange",
	"AimSwitchState",
	"OnSwitchPlayerCtrl",

	"BeforeCalculateCure",
	"BeforeCure",
	"Cure",
	"AfterCure",
	"Damage",
	"BeforeDamage",
	"AfterDamage",
	"BeforeGetDamageParam",
	"BeforeCalculateDamage",

	"PartnerShow",
	"PartnerLeave",
	"PartnerHide",
	"PartnerDeparture",

	"Hacking",
	"StopHacking",
	"HackingClickUp",
	"HackingClickDown",
	"HackingClickLeft",
	"HackingClickRight",
	"UpHackingActive",
	"DownHackingActive",
	"LeftHackingActive",
	"RightHackingActive",
	"PlayPartnerHackAnimation",
	"ExitHacking",
	"NpcHack",
	"CameraHack",
	"EnterBuildMode",
	"ExitBuildMode",
	"EnterCameraMode",
	"ExitCameraMode",
	"PVSetAttackTarget",
	"OnBuildConnect",
	"OnBuildDisconnect",
	"TempCreateBluePrint",

	"Warning",
	"KeyFrameAddEntity",
	"ConditionEvent",
	
	"ChangeRole",

	"OnLand",
	"OnAnimEvent",
	"OnDriveDrone",
	"OnStopDrive",
	"OnSetCarBroken",
	"OnCarBrake",
	"OnStopDriveDrone",
	"OnStopCommonDrive",
	"GetInCarEnd",
	"GetOffCarEnd",
	"DisableGetOffCar",
	"DoBehaviorCrossSpace",
	"onDroneDrive",
	"OnTouchAddSpeed",
	"onTrackPointMoveEnd",
	"OnStaminaOverdrawn",
	"LeaveFighting",
	"Kill",
	"OnEnemyFirstInFight",

	"RemoveLevel",
	"CreateLevelOccupancyFail",
	"FinishLevel",

	--UI
	"ChangeForeground",
	"ChangeBackground",
	"ChargeBeforeChange",
	"SkillTriggerLimitTimeOver",
	"ChargeChanged",
	"CastSkillCostBefore",
	"CastSkillCostAfter",
	"BeforePartnerReplaced",
	"AfterPartnerReplaced",
	"QTEChangeRole",
	"OnStealEntityGoods",
	"WorldInteractClick",
	"TopTargetClose",
	"OnGuideImageTips",
	"BackGroundEnd",
	"OnGuideStart",
	"OnGuideFinish",
	"KeyInput",
	"PartnerHackBuildClick",
	"CompleteAtomize",
	"QuitAtomize",
    "ClickControlDroneUp",
    "ClickControlDroneRight",
    "ClickControlDroneDown",
    "ClickControlDroneLeft",
    "MercenaryHuntAreaState",
    "CatchPartnerEnd",
    "OnExitShop",
	"OnPartnerBuildSuccess",
	"OnTakeBuilding",
	"OnExitTakeBuilding",
	"ChangeRootJointState",
	"OnExitBuilding",
	"OnActiveJointEntity",
	"OnBuildStateChange",
	"OnUpdateDiaplayInteractItem",
	"OnCountDownFinishEvent",

    "MailingActive",
    "MailingExchangeFinish",
    "MailingExchangeBeforeFinish",

    "StoryStartEvent",
    "StoryEndEvent",
    "StorySelectEvent",
    "StoryPassEvent",
	"ClueUnlock",
	"ClueFullUnlock",
	"ExploreStartEvent",
	"ExploreEndEvent",
	"ClueEnterView",
	"EnterClueArea",

    "UnlockConditionSuc",
	"TrafficLightChange",
	"BeforeTransport",
	"OnTransport",

	"EnterQTE",
	"ClickQTE",
	"ExitQTE",
	"EndAssassinQTE",
	"TriggerResourceEcoHit",

	"BaraginOnExit",
	"AbilityWheelFreePartnerSkill",
	"OnPhotoClick",

	"CoreUI1007OnOut",
	
	"DuplicateCountdownFinish",
	
	"InformCameraBlendState",

	"EntryPhotoFrame",
	"ExitPhotoFrame",

	"OnPhotoEnter",	
	"OnPhotoExit",	
	"OnPhotoClickEnd",

	"BegainHackingClickUp",
	"BegainHackingClickDown",
	"BegainHackingClickLeft",
	"BegainHackingClickRight",

	"PartnerHenshinStart",

	"RecvConcludeProbability",
	"ConcludePartner",
	"ConcludePartnerSuc",

	"LevelInstructionComplete",
	"NpcBindTask",
	"EcoEntityStateUpdate",		-- 生态服务器状态修改
	"CreateEcoGroupEntity",		-- 带生态群组的实体创建
}
