---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/21 10:02
---

CameraInputHandle = BaseClass("CameraInputHandle", BaseInputHandle)

function CameraInputHandle:Init(fight, entity, config)
    self.fight = fight
    self.entity = entity
    self.config = config
end

function CameraInputHandle:Hacking()
    local ctrlEntity = Fight.Instance.playerManager:GetPlayer():GetCtrlEntityObject()
    if not ctrlEntity.stateComponent:IsHacking() then
        Fight.Instance.playerManager:GetPlayer():SetPosNRotRecord()
        ctrlEntity.values["HackingCamera"] = true
        ctrlEntity.clientEntity.clientTransformComponent:SetGroupVisible("Root", false)
        ctrlEntity.stateComponent:SetHackState(FightEnum.HackState.Hacking)
    end

    BehaviorFunctions.AddBuff(1, 1, 1000084)

    ctrlEntity.stateComponent:SetHackingType(FightEnum.HackingType.Camera)
    ctrlEntity.stateComponent:SetHackingMoveState(false)
    BehaviorFunctions.SetCameraState(FightEnum.CameraState.Monitor)

    local camera = CameraManager.Instance.states[FightEnum.CameraState.Monitor]
    local target = self.entity.clientEntity.clientTransformComponent.transform:Find("Monitor01/CameraTarget")
    camera.mainTarget = target
	camera.cinemachineCamera.m_Follow = target
    camera.target = target
	camera.cinemachineCamera.m_LookAt = target
    ctrlEntity.transformComponent:SetPosition(self.entity.transformComponent.position.x, self.entity.transformComponent.position.y, self.entity.transformComponent.position.z)
end

function CameraInputHandle:StopHacking()
    local recordPos = Fight.Instance.playerManager:GetPlayer():GetRecordPosition()
    local recordRot = Fight.Instance.playerManager:GetPlayer():GetRecordRotation()
    local ctrlEntity = Fight.Instance.playerManager:GetPlayer():GetCtrlEntityObject()

    ctrlEntity.stateComponent:SetHackingType()
    ctrlEntity.stateComponent:SetHackingMoveState(true)
    BehaviorFunctions.SetCameraState(FightEnum.CameraState.Operating)
	BehaviorFunctions.Pause()
	local callBack = function()
        local camera = CameraManager.Instance.states[FightEnum.CameraState.Monitor]
        local target = ctrlEntity.clientEntity.clientTransformComponent.transform:Find("CameraTarget")
        camera.mainTarget = target
        camera.cinemachineCamera.m_Follow = target
        camera.target = target
        camera.cinemachineCamera.m_LookAt = target

        ctrlEntity.values["HackingCamera"] = true
		ctrlEntity.transformComponent:SetPosition(recordPos.x, recordPos.y, recordPos.z)
        ctrlEntity.transformComponent:SetRotation(recordRot)
        ctrlEntity.clientEntity.clientTransformComponent:SetGroupVisible("Root", true)
        ctrlEntity.stateComponent:SetHackState(FightEnum.HackState.Waiting)
		BehaviorFunctions.Resume()
	end
	local resLoad = MapResourcesPreload.New(recordPos.x, recordPos.y, recordPos.z, callBack)
	resLoad:DoPreload(true)
end

function CameraInputHandle:ClickUp(down)
    if down then
        self:Hacking()
    end
end

function CameraInputHandle:Update()
    local camera = CameraManager.Instance.states[FightEnum.CameraState.Monitor].camera
    local curPos = camera.transform.position
    local selfPos = self.entity.transformComponent:GetPosition()

    local distance = BehaviorFunctions.GetDistanceFromPos(curPos, selfPos)
    if distance <= 0.35 then
        BehaviorFunctions.RemoveBuff(1, 1000084)
    end
end